name: ihs
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.5.0
  - mysql-libs=8.0.21
  - geoplot=0.4.1
  - jupyterlab=2.2.8
  - mysql-common=8.0.21
  - python_abi=3.7
  - ipyleaflet=0.13.3
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.6.3
  - jupyterlab_pygments=0.1.1
  - jupyterlab_server=1.2.0
  - notebook=6.1.4
  - numpy=1.19.1
  - openssl=1.1.1h
  - pickleshare=0.7.5
  - pillow=7.2.0
  - python=3.7.8
  - python-dateutil=2.8.1
  - python-graphviz=0.14.1
  - pyyaml=5.3.1
  - setuptools=49.6.0
  - pip=20.2
  - sqlite=3.33.0
  - wheel=0.35.1
  - yaml=0.2.5
  - pip:
    - boto3==1.16.15
    - asn1crypto==1.4.0
    - astroid==2.4.2
    - autopep8==1.5.4
    - azure-common==1.1.25
    - azure-core==1.8.2
    - azure-storage-blob==12.5.0
    - bokeh==2.2.1
    - cloudpickle==1.6.0
    - cryptography==2.9.2
    - distributed==2.27.0
    - et-xmlfile==1.0.1
    - fsspec==0.8.2
    - geopy==1.23.0
    - heapdict==1.0.1
    - iniconfig==1.1.1
    - isodate==0.6.0
    - isort==5.6.4
    - jaydebeapi==1.2.3
    - jdcal==1.4.1
    - jmespath==0.10.0
    - jpype1==1.1.2
    - jupyter-contrib-core==0.3.3
    - jupyter-nbextensions-configurator==0.4.1
    - lazy-object-proxy==1.4.3
    - locket==0.2.0
    - lxml==4.5.2
    - matplotlib==3.3.1
    - mccabe==0.6.1
    - msgpack==1.0.0
    - msrest==0.6.19
    - openpyxl==3.0.5
    - oscrypto==1.2.1
    - partd==1.1.0
    - peppercorn==0.6
    - pip==20.2.4
    - pluggy==0.13.1
    - psutil==5.7.2
    - py==1.9.0
    - pyarrow==0.17.1
    - pycodestyle==2.6.0
    - pycryptodomex==3.9.8
    - pyjwt==1.7.1
    - pylint==2.6.0
    - pyodbc==4.0.30
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - pytest==6.1.2
    - requests==2.23.0
    - s3transfer==0.3.3
    - sortedcontainers==2.2.2
    - sqlalchemy==1.3.19
    - toml==0.10.2
    - toolz==0.11.0
    - typed-ast==1.4.1
    - typing-extensions==3.7.4.3
    - wrapt==1.12.1
    - xlrd==1.2.0
    - xlsxwriter==1.3.5
    - zict==2.0.0
    - fastparquet==0.4.1
