
clusters:
  spark:
    host: ''
    username: ''
    password: ''
  kafka:
    host: 'localhost'
    port: '9094'

databases:
    postfix: 3
    mongodb:
        dev:
            host: 'localhost'
            username: ''
            password: ''
            db_name: ''
            port: 27017   

cron:
  amount: 5
  range: 'hours'