
clusters:
  spark:
    host: ''
    username: ''
    password: ''
    partitions:  2100
    cores: 5
    memory: 11
  kafka:
    host: 'localhost'
    port: '9094'

databases:
    postfix: 3
    mongodb:
        dev:
            host: '127.0.0.1'
            username: ''
            password: ''
            db_name: ''
            port: 27017   

cron:
  amount: 5
  range: 'hours'